//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film_Database__SQL___VS_Practice_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int ID { get; set; }
        public string FilmName { get; set; }
        public Nullable<int> Year { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Actors { get; set; }
    }
}
